### ISSUE TITLE
Using Turbolinks events and options

### ISSUE THREAD

**Issue by olliekav** [ssorallen/turbo-react#14]
Is this possible, I can't seem to hook into them at the moment? For example I want to use
```
data-no-turbolink
```
And the ProgressBar

**Comment by ssorallen** [comment]
Can you give an example of `data-no-turbolink` not working for you? I tried it on the demo app and it worked like this:

```html
<p><a class="btn btn-primary" href="/" data-no-turbolink>Re-request this page</a></p>
```

**Comment by ssorallen** [comment]
As of 0.6.0, you can enable the progress bar by accessing the `Turbolinks` global that Reactize exposes: https://github.com/ssorallen/turbo-react#enable-a-progress-bar-to-show-pageload-progress

**Comment by olliekav** [comment]
That's great, thanks. I think the 'data-no-turbolink' issue is me not binding my JS events properly for Turbolinks, it's for a responsive nav. Investigating that now.
