### ISSUE TITLE
<textarea> and <pre> content is not converted properly

### ISSUE THREAD

**Issue by sickslives** [ssorallen/turbo-react#22]
The following rules are affecting `<textarea>` and `<pre>` when the page renders:
>All lines having leading or trailing whitespace are trimmed, all newlines are 
>removed, adjacent text separated by newlines become separated by a single 
>space. Any whitespace tabs are replaced with spaces. Strings inside 
>expressions are unaffected.

Summarized from [this pull request](/facebook/react/pull/480). I was originally looking for a way to opt-out a specific element from this, but after reading how react normally works with JSX components I'm not sure how to address this if you're building your UI with something else.

**Comment by dg3n** [comment]
It looks like this is actually due to the [HTMLtoJSX converter](https://facebook.github.io/react/html-jsx.html). It doesn't produce the JSX necessary to maintain textarea and pre tag content, [here's a fiddle](https://jsfiddle.net/jyth3h65/3/) demonstrating this.

**Comment by sickslives** [comment]
Moved this to: reactjs/react-magic/#33 as that's where the HTMLtoJSX converter lives.

**Comment by sickslives** [comment]
fixed in reactjs/react-magic@8b90aa3

**Comment by ssorallen** [comment]
Perfect, thanks for the note. I will update turbo-react with the latest react-magic.

**Comment by sickslives** [comment]
Thanks! Don't forget the rails gem!

**Comment by ssorallen** [comment]
Pushed an updated version of the JS and of the Ruby gem with the update assets.

**Comment by tom-orrow** [comment]
Hi. A bit of explanation could be nice. How can I render textarea with new lines? Value attribute still replaces line breaks with spaces. Default value attribute seems not working.

**Comment by sickslives** [comment]
@tom-orrow this was fixed in reactjs/react-magic@8b90aa3, but broken again when turbo-react's version of turbolinks was updated to non-stable version, see #24.

**Comment by sickslives** [comment]
Actually I just realized I hadn't switched back to the original turbo_react-rails gem. @ssorallen your release doesn't appear to include the newline fixes, any idea?

**Comment by ssorallen** [comment]
@sickslives turbo-react does not bundle Turbolinks any more, so turbo-react needs to the react-magic fix in order to work with Edge Turbolinks.

Is there a release of react-magic with the fix? I can update both turbo-react and turbo-react_rails with it.

**Comment by sickslives** [comment]
@ssorallen The current master branch of react-magic includes the textarea/pre fix, I'm not sure why it didn't come through in your bundle. I got it working in my fork but since the file's minified I can't really tell why mine works and yours doesn't.

**Comment by ssorallen** [comment]
The commit to fix <textarea> and <pre> is not yet in a release for html-to-jsx. The latest is v0.2.4, but the commit is only in master: https://github.com/reactjs/react-magic/compare/release-0.2.4...master
