### ISSUE TITLE
global is not defined error

### ISSUE THREAD

**Issue by dm123455** [ssorallen/turbo-react#30]
I am trying to use turbolinks in our rails application. The gems that I was initially using are jquery-turbolinks and turbolinks. But my react component does not show up after adding them into my application. So I went ahead and added turbo_react-rails into my app(in addition to  jquery-turbolinks and turbolinks), but it throws 'global is not defined error'. What am I doing wrong?

**Comment by mjcloutier** [comment]
getting the same global is undefined.

```javascript
var originalReplaceChild =
  global.document.documentElement.replaceChild.bind(
    global.document.documentElement);
```

**Comment by mjcloutier** [comment]
Looks like getting this as well:

```javascript
var converter = new HTMLtoJSX({createClass: false});
```

Is there an extra dependency required to run this in a rails app?

**Comment by dLobatog** [comment]
I'm getting the same when evaluating `if (global.Turbolinks === undefined) {`, - global itself isn't defined.

**Comment by dLobatog** [comment]
I see the latest release uses `if (window.Turbolinks === undefined) {`, which is indeed defined on my setup too. @ssorallen can we expect a new release?

**Comment by ssorallen** [comment]
I just released the ['turbo_react-rails' gem](https://rubygems.org/gems/turbo_react-rails) with the version of the 'turbo-react' that fixes the `global` error. v0.9.0 should fix the issue you're seeing. Try upgrading your gems, and let me know if you see other problems.
