### ISSUE TITLE
HTML <input> tags will fail in JSXTransformer.transform

### ISSUE THREAD

**Issue by hallgren** [ssorallen/turbo-react#7]
`JSXTransformer.transform` expect all tags to end with a slash `</>` or a closing tag `<></>` but the `element.innerHTML` will transform a input tag to a single `<input>` tag with no ending / that will fail in the transform method. => `Expected corresponding XJS closing tag for input`

I don´t know if the issue is in the `.innerHTML` method or that `JSXTransformer.transform` should handle the `<input>` tag?

**Comment by ssorallen** [comment]
I confirmed this was fixed by integrating react-magic's HTML to JSX converter.
